include .env

build:
	make build-server
	make build-web

build-server:
	CGO_ENABLED=0 go build -ldflags="-s -w" -o ./dist/gestor-ultra ./cmd/main.go

build-web:
	cd web/ && PUBLIC_URL=$(CORS_ALLOW_ORIGIN) npm run build

run-web:
	cd web/ && PUBLIC_URL=$(CORS_ALLOW_ORIGIN) npm run dev

run-server:
	PORT=$(PORT) \
	POSTGRES_URI=$(POSTGRES_URI) \
	REDIS_URI=$(REDIS_URI) \
	AUTH_SECRET_KEY=$(AUTH_SECRET_KEY) \
	REPORTS_DIRECTORY=$(REPORTS_DIRECTORY) \
	PROMETHEUS_URL=$(PROMETHEUS_URL) \
	WEB_APP_DIRECTORY=$(WEB_APP_DIRECTORY) \
	CORS_ALLOW_ORIGIN=$(CORS_ALLOW_ORIGIN) \
	go run ./cmd/main.go server

run-scan:
	PORT=$(PORT) \
	POSTGRES_URI=$(POSTGRES_URI) \
	REDIS_URI=$(REDIS_URI) \
	AUTH_SECRET_KEY=$(AUTH_SECRET_KEY) \
	REPORTS_DIRECTORY=$(REPORTS_DIRECTORY) \
	PROMETHEUS_URL=$(PROMETHEUS_URL) \
	WEB_APP_DIRECTORY=$(WEB_APP_DIRECTORY) \
	CORS_ALLOW_ORIGIN=$(CORS_ALLOW_ORIGIN) \
	go run ./cmd/main.go scan

start-server: build
	PORT=$(PORT) \
	POSTGRES_URI=$(POSTGRES_URI) \
	REDIS_URI=$(REDIS_URI) \
	AUTH_SECRET_KEY=$(AUTH_SECRET_KEY) \
	REPORTS_DIRECTORY=$(REPORTS_DIRECTORY) \
	PROMETHEUS_URL=$(PROMETHEUS_URL) \
	CORS_ALLOW_ORIGIN=$(CORS_ALLOW_ORIGIN) \
	WEB_APP_DIRECTORY=$(WEB_APP_DIRECTORY) \
	ENVIROMENT="production"
	./dist/gestor-ultra server
