include .env

build:
	make build-server
	make build-web

build-server:
	CGO_ENABLED=0 go build -ldflags="-s -w" -o ./dist/gestor-ultra ./cmd/main.go

build-web:
	cd web/ && npm run build

run-web:
	cd web/ && PUBLIC_URL="http://localhost:$(PORT)" npm run dev

run-server:
	PORT=$(PORT) \
	POSTGRES_URI=$(POSTGRES_URI) \
	REDIS_URI=$(REDIS_URI) \
	AUTH_SECRET_KEY=$(AUTH_SECRET_KEY) \
	REPORTS_DIRECTORY=$(REPORTS_DIRECTORY) \
	PROMETHEUS_URL=$(PROMETHEUS_URL) \
	WEB_APP_DIRECTORY=$(WEB_APP_DIRECTORY) \
	CORS_ALLOW_ORIGIN=$(CORS_ALLOW_ORIGIN) \
	MONGODB_URI=$(MONGODB_URI) \
	go run ./cmd/main.go server

run-scan:
	PORT=$(PORT) \
	POSTGRES_URI=$(POSTGRES_URI) \
	REDIS_URI=$(REDIS_URI) \
	AUTH_SECRET_KEY=$(AUTH_SECRET_KEY) \
	REPORTS_DIRECTORY=$(REPORTS_DIRECTORY) \
	PROMETHEUS_URL=$(PROMETHEUS_URL) \
	WEB_APP_DIRECTORY=$(WEB_APP_DIRECTORY) \
	CORS_ALLOW_ORIGIN=$(CORS_ALLOW_ORIGIN) \
	MONGODB_URI=$(MONGODB_URI) \
	go run ./cmd/main.go scan

run-traffic:
	PORT=$(PORT) \
	POSTGRES_URI=$(POSTGRES_URI) \
	REDIS_URI=$(REDIS_URI) \
	AUTH_SECRET_KEY=$(AUTH_SECRET_KEY) \
	REPORTS_DIRECTORY=$(REPORTS_DIRECTORY) \
	PROMETHEUS_URL=$(PROMETHEUS_URL) \
	WEB_APP_DIRECTORY=$(WEB_APP_DIRECTORY) \
	CORS_ALLOW_ORIGIN=$(CORS_ALLOW_ORIGIN) \
	MONGODB_URI=$(MONGODB_URI) \
	go run ./cmd/main.go traffic $(DAY)

run-interface: 
	PORT=$(PORT) \
	POSTGRES_URI=$(POSTGRES_URI) \
	REDIS_URI=$(REDIS_URI) \
	AUTH_SECRET_KEY=$(AUTH_SECRET_KEY) \
	REPORTS_DIRECTORY=$(REPORTS_DIRECTORY) \
	PROMETHEUS_URL=$(PROMETHEUS_URL) \
	WEB_APP_DIRECTORY=$(WEB_APP_DIRECTORY) \
	CORS_ALLOW_ORIGIN=$(CORS_ALLOW_ORIGIN) \
	MONGODB_URI=$(MONGODB_URI) \
	go run ./cmd/main.go interface-bandwidth
