export const REGIONS = [
  { value: "Andina", label: "Región Andina" },
  { value: "Capital", label: "Región Capital" },
  { value: "Central", label: "Región Central" },
  { value: "Los Llanos", label: "Región Los Llanos" },
  { value: "Guayana", label: "Región Guayana" },
  { value: "Occidental", label: "Región Occidental" },
  { value: "Oriental", label: "Región Oriental" },
];

export const STATES_BY_REGION = {
  Andina: ["Mérida", "Táchira", "Trujillo"],
  Capital: ["Distrito Capital", "Miranda", "La Guaira"],
  Central: ["Aragua", "Carabobo", "Yaracuy"],
  "Los Llanos": ["Apure", "Barinas", "Cojedes", "Guárico", "Portuguesa"],
  Guayana: ["Amazonas", "Bolívar", "Delta Amacuro"],
  Occidental: ["Falcón", "Lara", "Zulia"],
  Oriental: ["Anzoátegui", "Monagas", "Nueva Esparta", "Sucre"],
};

export const MAP_STATE_TRANSLATER = {
  Amazonas: "AMAZONAS",
  Anzoátegui: "ANZOATEGUI",
  Apure: "APURE",
  Aragua: "ARAGUA",
  Barinas: "BARINAS",
  Bolívar: "BOLIVAR",
  Carabobo: "CARABOBO",
  Cojedes: "COJEDES",
  "Delta Amacuro": "DELTA AMACURO",
  "Distrito Capital": "DISTRITO CAPITAL",
  Falcón: "FALCON",
  Guárico: "GUARICO",
  Lara: "LARA",
  Mérida: "MERIDA",
  Miranda: "MIRANDA",
  Monagas: "MONAGAS",
  "Nueva Esparta": "NUEVA ESPARTA",
  Portuguesa: "PORTUGUESA",
  Sucre: "SUCRE",
  Táchira: "TACHIRA",
  Trujillo: "TRUJILLO",
  "La Guaira": "VARGAS",
  Yaracuy: "YARACUY",
  Zulia: "ZULIA",
}
