FROM python:alpine AS build

WORKDIR /app

COPY ./chatbot/requirements.txt requirements.txt

RUN python -m venv ./venv
RUN source ./venv/bin/activate
RUN pip install -r requirements.txt

COPY  ./config.json .
COPY chatbot/ .

EXPOSE 8000

CMD ["python", "main.py"]
