FROM python:alpine AS build

WORKDIR /app

COPY ./requirements.txt .

RUN python -m venv ./venv
RUN source ./venv/bin/activate
RUN pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "main.py"]
